// <auto-generated />
namespace DeliveryDBCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Orders_and_StatusesOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Orders_and_StatusesOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201547406_add_Orders_and_StatusesOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
